language: emacs-lisp
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
    - $HOME/.evm
    - $HOME/.cask
    - /usr/local/evm
env:
  global:
    - PATH=$HOME/.pyenv/bin:$HOME/.pyenv/shims:$HOME/.evm/bin:$HOME/.cask/bin:$PATH
before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
install:
  - while true ; do echo -n . ; sleep 0.5 ; done & ; ansible-playbook -i inventories/travis playbook.yml
script:
  - tox
  - cask exec ert-runner
after_success:
  - coveralls-merge emacs-coveralls.json
