language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
cache:
  directories:
  - $HOME/.cache/pip/wheels
install:
  - pip install -U pip wheel setuptools
  - pip install .
  - pip install -r requirements.txt
script:
  - pip freeze
  - pytest
