language: emacs-lisp
env:
  global:
    - PATH=$HOME/.emacs/emacs-24.3/bin:$HOME/.emacs/emacs-24.4/bin:$HOME/.emacs/emacs-24.5/bin:$HOME/.pyenv/bin:$HOME/.pyenv/shims:$HOME/.cask/bin:$PATH
install:
  - ./script/deploy.sh
script:
  - tox
  - ./script/ert.sh
after_success:
  - coveralls-merge emacs-coveralls.json
