language: python

before_install:
  - curl -L http://bootstrap.saltstack.org | sudo sh
  - sudo cp -r salt/states /srv/states
  - sudo cp salt/minion /etc/salt/minion

install:
  - sudo salt-call state.highstate pillar="{'build_dir':'$TRAVIS_BUILD_DIR'}" --local

script:
  - tox

after_success:
  - coveralls
