- name: create emacs directory
  file: dest="{{emacs_directory}}" state=directory mode=0777
  become: yes
- name: get emacs sources
  get_url:
    url="http://ftp.gnu.org/gnu/emacs/{{item}}.tar.xz"
    dest="{{emacs_directory}}"
  with_items: "{{emacs_versions}}"
- name: create emacs source directory
  file: dest="{{emacs_directory}}/{{item}}-src" state=directory
  with_items: "{{emacs_versions}}"
- name: unpack emacs sources
  unarchive:
    src="{{emacs_directory}}/{{item}}.tar.xz"
    dest="{{emacs_directory}}/{{item}}-src"
    copy=no
  with_items: "{{emacs_versions}}"
- name: configure emacs build
  shell:
    ./configure --prefix="{{emacs_directory}}/{{item}}"
    chdir="{{emacs_directory}}/{{item}}-src/{{item}}"
  with_items: "{{emacs_versions}}"
- name: build emacs
  command:
    make
    chdir="{{emacs_directory}}/{{item}}-src/{{item}}"
  with_items: "{{emacs_versions}}"
- name: install emacs
  command:
    make install
    chdir="{{emacs_directory}}/{{item}}-src/{{item}}"
  with_items: "{{emacs_versions}}"
